import type { RecordFormValues } from './useTmdbRecordSearch';
import { PLATFORMS } from '../../../shared/lib/constants';
import { formatMovieTime, parseTimeToSeconds } from './recordFormModel';

interface PlaybackFieldsProps {
  form: RecordFormValues; isEpisodic: boolean; movieProgressStr: string; movieDurationStr: string;
  onTotalEpisodesChange: (value: number | null) => void;
  onMovieProgressChange: (value: string, seconds: number | null) => void; onMovieDurationChange: (value: string, seconds: number | null) => void; onPlatformChange: (value: string) => void;
}

export default function PlaybackFields({ form, isEpisodic, movieProgressStr, movieDurationStr, onTotalEpisodesChange, onMovieProgressChange, onMovieDurationChange, onPlatformChange }: PlaybackFieldsProps) {
  return <>
    {isEpisodic && <div><label className="block text-sm font-medium text-gray-700 mb-1">总集数<span className="ml-1.5 text-xs text-gray-400 font-normal">（可选）</span></label><div className="flex items-center gap-2"><input type="number" min="1" value={form.totalEpisodes ?? ''} onChange={event => onTotalEpisodesChange(event.target.value ? parseInt(event.target.value, 10) : null)} placeholder="如 12" className="w-32 px-3 py-2 rounded-xl border border-gray-200 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 transition" /><span className="text-sm text-gray-400">集</span>{form.totalEpisodes && <span className="text-xs text-indigo-600 bg-indigo-50 px-2 py-1 rounded-full">{form.progress ? `${form.progress} / ${form.totalEpisodes} 集` : `共 ${form.totalEpisodes} 集`}</span>}</div></div>}
    {!isEpisodic && <div className="flex flex-col gap-3"><div className="grid grid-cols-2 gap-3"><div><label className="block text-sm font-medium text-gray-700 mb-1">当前看到<span className="ml-1.5 text-xs text-gray-400 font-normal">（可选）</span></label><input type="text" value={movieProgressStr} onChange={event => { const value = event.target.value; onMovieProgressChange(value, parseTimeToSeconds(value)); }} placeholder="如 1h 30m 45s" className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 transition" /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">电影总时长<span className="ml-1.5 text-xs text-gray-400 font-normal">（可选）</span></label><input type="text" value={movieDurationStr} onChange={event => { const value = event.target.value; onMovieDurationChange(value, parseTimeToSeconds(value)); }} placeholder="如 2h 30m" className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 transition" /></div></div>{form.movieProgress !== null && <div className="text-xs text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-xl inline-flex items-center self-start">已看：{formatMovieTime(form.movieProgress)}{form.movieDuration && form.movieDuration > 0 && <span className="ml-2 text-indigo-400">/ {formatMovieTime(form.movieDuration)}&nbsp;({Math.round((form.movieProgress / form.movieDuration) * 100)}%)</span>}</div>}</div>}
    {isEpisodic && <div><label className="block text-sm font-medium text-gray-700 mb-1">平台</label><input type="text" value={form.platform} onChange={event => onPlatformChange(event.target.value)} placeholder="Netflix / 爱奇艺 / B站..." list="platform-list" className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 transition" /><datalist id="platform-list">{PLATFORMS.map(platform => <option key={platform} value={platform} />)}</datalist></div>}
  </>;
}
