import { useCallback, useState } from 'react';
import type { UpdateWatchRecord, WatchRecord } from '../../../shared/types';
import type { SyncConflict } from '../../../shared/lib/webdav';
import type { SyncRuntimeState } from '../../../shared/lib/database';
import type { NoticeTone } from '../../../shared/lib/feedback';
import { notifyOperationFailure } from '../../../shared/lib/feedback';
import { formatWebDavTargetUrl } from '../../../shared/lib/webdavDisplay';
import { useAccessibleDialog } from '../../../shared/lib/useAccessibleDialog';
import { useSettingsBootstrap } from '../hooks/useSettingsBootstrap';
import { useBasicSettings } from '../hooks/useBasicSettings';
import { useSyncSettings } from '../hooks/useSyncSettings';
import { useRecoveryPoints } from '../hooks/useRecoveryPoints';
import { usePosterCache } from '../hooks/usePosterCache';
import { useDatabaseMaintenance } from '../hooks/useDatabaseMaintenance';
import { useImportExport } from '../hooks/useImportExport';
import { useBatchMetadata } from '../hooks/useBatchMetadata';
import CategoriesTab from './tabs/CategoriesTab';
import AboutTab from './tabs/AboutTab';
import BasicSettingsTab from './tabs/BasicSettingsTab';
import SyncSettingsTab from './tabs/SyncSettingsTab';
import ImportExportPanel from './tools/ImportExportPanel';
import RecoveryPointsPanel from './tools/RecoveryPointsPanel';
import PosterCachePanel from './tools/PosterCachePanel';
import DatabaseMaintenancePanel from './tools/DatabaseMaintenancePanel';
import BatchMetadataPanel from './tools/BatchMetadataPanel';

interface SettingsModalProps { initialTab?: 'basic' | 'sync' | 'categories' | 'tools' | 'about'; onClose: () => void; records: WatchRecord[]; onImport: (records: WatchRecord[]) => void | Promise<void>; onSync?: () => Promise<{ ok: boolean; error?: string; conflictCount?: number }>; onUpdateRecord: (id: string, updates: UpdateWatchRecord) => Promise<void>; onDatabaseRestored: () => Promise<WatchRecord[]>; syncInterval: number; onSyncIntervalChange: (val: number) => void; pullIntervalMinutes: number; onPullIntervalChange: (val: number) => void; syncRuntime: SyncRuntimeState | null; onNotify?: (tone: NoticeTone, message: string) => void; }

export default function SettingsModal({ initialTab = 'basic', onClose, records, onImport, onSync, onUpdateRecord, onDatabaseRestored, syncInterval, onSyncIntervalChange, pullIntervalMinutes, onPullIntervalChange, syncRuntime, onNotify }: SettingsModalProps) {
  const [activeTab, setActiveTab] = useState<NonNullable<SettingsModalProps['initialTab']>>(initialTab);
  const showFailure = useCallback((scope: string, action: string, error: unknown, setStatus?: (message: string) => void) => { const message = notifyOperationFailure(scope, action, error, onNotify ?? (() => undefined)); setStatus?.(`❌ ${message}`); }, [onNotify]);
  const showSuccess = useCallback((message: string) => onNotify?.('success', message), [onNotify]);
  const bootstrap = useSettingsBootstrap({ records, onNotify, showFailure });
  const basic = useBasicSettings({ tmdbKey: bootstrap.tmdbKey, setTmdbKey: bootstrap.setTmdbKey, setTmdbSaved: bootstrap.setTmdbSaved, setSyncStatus: bootstrap.setSyncStatus, proxy: bootstrap.proxy, showFailure, showSuccess });
  const sync = useSyncSettings({ records, onSync, onImport, onDatabaseRestored, onNotify, showFailure, showSuccess, username: bootstrap.username, setUsername: bootstrap.setUsername, password: bootstrap.password, setPassword: bootstrap.setPassword, webdavUrl: bootstrap.webdavUrl, setWebdavUrl: bootstrap.setWebdavUrl, saved: bootstrap.saved, setSaved: bootstrap.setSaved, editingTarget: bootstrap.editingTarget, setEditingTarget: bootstrap.setEditingTarget, targetRegistry: bootstrap.targetRegistry, setTargetRegistry: bootstrap.setTargetRegistry, syncStatus: bootstrap.syncStatus, setSyncStatus: bootstrap.setSyncStatus, syncConflicts: bootstrap.syncConflicts, setSyncConflicts: bootstrap.setSyncConflicts, syncInterval, onSyncIntervalChange, pullIntervalMinutes, onPullIntervalChange });
  const recovery = useRecoveryPoints({ records, onDatabaseRestored, onNotify, showFailure, showSuccess });
  const poster = usePosterCache({ showFailure, showSuccess });
  const maintenance = useDatabaseMaintenance({ showFailure, showSuccess });
  const file = useImportExport({ records, onImport, onDatabaseRestored, onNotify, showFailure, showSuccess });
  const batch = useBatchMetadata({ records, tmdbSaved: bootstrap.tmdbSaved, initialBatchNoDataState: bootstrap.batchNoDataState, onUpdateRecord, onDatabaseRestored, onNotify, showFailure, showSuccess });
  const activeTarget = bootstrap.targetRegistry?.targets.find(target => target.id === bootstrap.targetRegistry?.activeTargetId); const activeTargetDisplay = formatWebDavTargetUrl(activeTarget?.normalizedUrl ?? bootstrap.webdavUrl); const automaticSyncPaused = syncRuntime?.scheduler.paused ?? false;
  const refreshRecoveryPoints = recovery.refreshRecoveryPoints; const refreshPosterCache = poster.refreshPosterCache;
  const openTools = useCallback(() => { setActiveTab('tools'); void refreshRecoveryPoints(); void refreshPosterCache(); }, [refreshPosterCache, refreshRecoveryPoints]);
  const dialogRef = useAccessibleDialog<HTMLDivElement>({ onEscape: () => { if (batch.batchSyncing) batch.handleCancel(); else onClose(); } });
  return <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="settings-dialog-title" tabIndex={-1} className="fixed inset-0 z-50 flex bg-gray-50 text-gray-800 font-sans overflow-hidden animate-fade-in animate-duration-200">
    <div className="w-64 bg-white border-r border-gray-200 flex flex-col justify-between shrink-0 select-none"><div><div className="px-6 py-8 border-b border-gray-100"><h2 id="settings-dialog-title" className="text-xl font-black text-gray-900 flex items-center gap-2"><span>⚙️</span> 设置中心</h2><p className="text-[10px] text-gray-400 font-mono mt-1 uppercase tracking-wider">System Settings</p></div><nav className="p-4 space-y-1">
      <button onClick={() => setActiveTab('basic')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${activeTab === 'basic' ? 'bg-indigo-50 text-indigo-700 font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'}`}><span className="text-lg">🌐</span> 基础配置</button><button onClick={() => setActiveTab('sync')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${activeTab === 'sync' ? 'bg-indigo-50 text-indigo-700 font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'}`}><span className="text-lg">☁️</span> 云端同步</button><button onClick={() => setActiveTab('categories')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${activeTab === 'categories' ? 'bg-indigo-50 text-indigo-700 font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'}`}><span className="text-lg">🏷️</span> 类型与标签</button><button onClick={openTools} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${activeTab === 'tools' ? 'bg-indigo-50 text-indigo-700 font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'}`}><span className="text-lg">🛠️</span> 系统工具</button><button onClick={() => setActiveTab('about')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold transition-colors ${activeTab === 'about' ? 'bg-indigo-50 text-indigo-700 font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'}`}><span className="text-lg">ℹ️</span> 关于</button>
    </nav></div><div className="p-4 border-t border-gray-100"><button onClick={batch.batchSyncing ? batch.handleCancel : onClose} className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl border border-gray-200 hover:bg-gray-50 text-sm font-bold text-gray-700 transition-colors shadow-sm"><span>←</span>{batch.batchSyncing ? '安全停止任务' : '返回主页'}</button></div></div>
    <div className="min-h-0 min-w-0 flex-1 overflow-y-auto bg-gray-50/50 p-6 pr-4 sm:p-10 sm:pr-6 md:p-12 md:pr-8 custom-scrollbar"><div className="max-w-3xl mx-auto space-y-8">
      {activeTab === 'basic' && <BasicSettingsTab tmdbSaved={bootstrap.tmdbSaved} tmdbKey={bootstrap.tmdbKey} proxy={bootstrap.proxy} onTmdbKeyChange={bootstrap.setTmdbKey} onProxyChange={bootstrap.setProxy} onSaveTmdbKey={() => void basic.handleSaveTmdbKey()} onClearTmdbKey={() => void basic.handleClearTmdbKey()} onSaveProxy={() => void basic.handleSaveProxy()} />}
      {activeTab === 'sync' && <SyncSettingsTab username={bootstrap.username} password={bootstrap.password} webdavUrl={bootstrap.webdavUrl} saved={bootstrap.saved} editingTarget={bootstrap.editingTarget} targetRegistry={bootstrap.targetRegistry} activeTarget={activeTarget} activeTargetDisplay={activeTargetDisplay} automaticSyncPaused={automaticSyncPaused} syncStatus={bootstrap.syncStatus} importStatus={sync.importStatus} syncConflicts={bootstrap.syncConflicts} localInterval={sync.localInterval} localPullInterval={sync.localPullInterval} syncRuntime={syncRuntime} onUsernameChange={bootstrap.setUsername} onPasswordChange={bootstrap.setPassword} onWebdavUrlChange={bootstrap.setWebdavUrl} onEditingTargetChange={bootstrap.setEditingTarget} onSave={() => void sync.handleSave()} onClear={() => void sync.handleClear()} onSync={() => void sync.handleSync()} onImport={() => void sync.handleImport()} onImportLegacyChanges={() => void sync.handleImportLegacyChanges()} onResolveConflict={(conflict: SyncConflict, resolution) => void sync.handleResolveConflict(conflict, resolution)} onLocalIntervalChange={sync.setLocalInterval} onSaveInterval={() => void sync.handleSaveInterval()} onLocalPullIntervalChange={sync.setLocalPullInterval} onSavePullInterval={() => void sync.handleSavePullInterval()} />}
      {activeTab === 'categories' && <CategoriesTab records={records} />}
      {activeTab === 'tools' && <div className="space-y-6 animate-fade-in animate-duration-200"><div><h3 className="text-2xl font-black text-gray-900">🛠️ 系统工具</h3><p className="text-xs text-gray-400 mt-1">本地数据维护、高级清理、以及缺失的元数据同步补全</p></div><ImportExportPanel onImportLocal={() => file.handleImportLocal()} onExport={() => void file.handleExport()} /><RecoveryPointsPanel recoveryPoints={recovery.recoveryPoints} recoveryStatus={recovery.recoveryStatus} recoveryBusyId={recovery.recoveryBusyId} onRefresh={() => void recovery.refreshRecoveryPoints()} onRestore={point => void recovery.handleRestoreRecoveryPoint(point)} onToggleRetention={point => void recovery.handleToggleRecoveryRetention(point)} onDelete={point => void recovery.handleDeleteRecoveryPoint(point)} onOpenBackupDirectory={() => void recovery.handleOpenBackupDirectory()} /><PosterCachePanel posterCache={poster.posterCache} posterCacheStatus={poster.posterCacheStatus} posterCacheBusy={poster.posterCacheBusy} onRefresh={() => void poster.refreshPosterCache()} onClean={mode => void poster.handleCleanPosterCache(mode)} /><DatabaseMaintenancePanel vacuumStatus={maintenance.vacuumStatus} onVacuum={() => void maintenance.handleVacuum()} /><BatchMetadataPanel tmdbSaved={bootstrap.tmdbSaved} batchNoDataState={batch.batchNoDataState} batchPhase={batch.batchPhase} batchStatus={batch.batchStatus} batchProgress={batch.batchProgress} batchTotal={batch.batchTotal} batchPlan={batch.batchPlan} batchResults={batch.batchResults} batchChoosingId={batch.batchChoosingId} batchSyncing={batch.batchSyncing} onClearNoData={() => void batch.handleClearNoData()} onPrepare={() => void batch.handlePrepare()} onCancel={batch.handleCancel} onApply={plans => void batch.handleApply(plans)} onSelectCandidate={(row, match) => void batch.handleSelectCandidate(row, match)} onReset={batch.resetBatch} /></div>}
      {activeTab === 'about' && <AboutTab />}
    </div></div>
  </div>;
}
