import { useState } from 'react';
import { BUILD_INFO } from '../../../../shared/lib/buildInfo';
import { formatGitCommitTime } from '../../../../shared/lib/buildInfoCore';

export default function AboutTab() {
  const [commitCopied, setCommitCopied] = useState(false);
  async function copyCommit() {
    if (BUILD_INFO.gitCommit === 'unknown') return;
    try { await navigator.clipboard.writeText(BUILD_INFO.gitCommit); setCommitCopied(true); setTimeout(() => setCommitCopied(false), 1600); } catch { setCommitCopied(false); }
  }
  return <div className="space-y-6 animate-fade-in animate-duration-200" data-testid="about-settings"><div><h3 className="text-2xl font-black text-gray-900">ℹ️ 关于</h3><p className="mt-1 text-xs text-gray-400">查看当前程序包对应的产品与源代码版本</p></div><div className="min-w-0 space-y-6 rounded-3xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex min-w-0 items-center gap-4 border-b border-gray-100 pb-5"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-indigo-50 text-3xl">🎬</div><div className="min-w-0"><p className="truncate text-xl font-black text-gray-900">WatchTracker</p><p className="text-sm font-semibold text-indigo-600">影视追踪</p></div></div><dl className="space-y-4 text-sm"><div className="grid min-w-0 grid-cols-1 gap-1 sm:grid-cols-[7rem_minmax(0,1fr)] sm:items-center sm:gap-4"><dt className="font-semibold text-gray-500">产品版本</dt><dd className="min-w-0 font-mono font-bold text-gray-800" data-testid="about-product-version">v{BUILD_INFO.productVersion}</dd></div><div className="grid min-w-0 grid-cols-1 gap-1 sm:grid-cols-[7rem_minmax(0,1fr)] sm:items-center sm:gap-4"><dt className="font-semibold text-gray-500">Git commit</dt><dd className="flex min-w-0 flex-wrap items-center gap-2"><code className="max-w-full truncate rounded-lg bg-gray-100 px-2.5 py-1 font-mono text-xs text-gray-700" data-testid="about-git-commit" title={BUILD_INFO.gitCommit}>{BUILD_INFO.shortCommit}</code><button type="button" onClick={() => void copyCommit()} disabled={BUILD_INFO.gitCommit === 'unknown'} className="rounded-lg border border-gray-200 px-2.5 py-1 text-xs font-bold text-gray-500 transition-colors hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-40">{commitCopied ? '已复制' : '复制完整编码'}</button></dd></div><div className="grid min-w-0 grid-cols-1 gap-1 sm:grid-cols-[7rem_minmax(0,1fr)] sm:items-center sm:gap-4"><dt className="font-semibold text-gray-500">提交时间</dt><dd className="min-w-0 break-words text-gray-700" data-testid="about-commit-time">{formatGitCommitTime(BUILD_INFO.gitCommitTime)}</dd></div></dl>{BUILD_INFO.fallback && <p className="rounded-xl border border-amber-100 bg-amber-50 p-3 text-xs leading-relaxed text-amber-700">当前为开发环境，未能读取完整 Git 构建信息；正式构建会写入实际提交编码和提交时间。</p>}<p className="text-xs leading-relaxed text-gray-400">此处时间来自 Git 提交记录，并按当前系统时区显示，不代表程序的构建或安装时间。</p></div></div>;
}
