interface BasicSettingsTabProps {
  tmdbSaved: boolean; tmdbKey: string; proxy: string;
  onTmdbKeyChange: (value: string) => void; onProxyChange: (value: string) => void;
  onSaveTmdbKey: () => void; onClearTmdbKey: () => void; onSaveProxy: () => void;
}

export default function BasicSettingsTab({ tmdbSaved, tmdbKey, proxy, onTmdbKeyChange, onProxyChange, onSaveTmdbKey, onClearTmdbKey, onSaveProxy }: BasicSettingsTabProps) {
  return <div className="space-y-6 animate-fade-in animate-duration-200"><div><h3 className="text-2xl font-black text-gray-900">🌐 基础配置</h3><p className="text-xs text-gray-400 mt-1">配置核心服务密钥以及本地代理网络环境</p></div>
    <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100 space-y-4"><div className="flex items-center justify-between border-b border-gray-50 pb-4"><div className="flex items-center gap-2.5"><span className="text-2xl">🔍</span><div><h4 className="font-bold text-gray-800">影视元数据配置</h4><p className="text-[11px] text-gray-400">调用 TMDB 接口以获取影片海报、年份及详情信息</p></div></div>{tmdbSaved && <span className="text-xs px-2.5 py-0.5 bg-green-50 text-green-700 border border-green-200 rounded-full font-semibold">受 Windows 保护</span>}</div>
      {!tmdbSaved ? <div className="space-y-3"><input type="password" placeholder="输入 TMDB API KEY (V3)" value={tmdbKey} onChange={event => onTmdbKeyChange(event.target.value)} className="w-full px-4 py-2.5 text-sm border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all" /><p className="text-[10px] text-gray-400">💡 密钥保存在当前 Windows 用户的凭据管理器中，不会写入 data 目录；移动到其他电脑或 Windows 用户后需要重新输入。可以在 TMDB 官网的个人设置中申请。</p><button onClick={onSaveTmdbKey} className="py-2.5 px-6 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold transition-colors disabled:opacity-50" disabled={!tmdbKey.trim()}>保存密钥</button></div> : <div className="flex items-center justify-between bg-gray-50 rounded-2xl p-4"><div className="flex items-center gap-2"><span className="text-green-600">✓</span><span className="text-sm text-gray-700 font-medium">TMDB API 密钥已受 Windows 保护</span></div><button onClick={onClearTmdbKey} className="text-xs text-red-500 hover:underline font-bold transition-all">清除并重置</button></div>}
    </div>
    <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100 space-y-4"><div className="flex items-center gap-2.5 border-b border-gray-50 pb-4"><span className="text-2xl">🌐</span><div><h4 className="font-bold text-gray-800">网络代理 (可选)</h4><p className="text-[11px] text-gray-400">若你在获取 TMDB 元数据时遇到网络问题，请配置代理服务</p></div></div><p className="text-xs text-gray-500">支持 HTTP / SOCKS 代理格式。例如：`http://127.0.0.1:7890`。若无网络墙阻拦，请保持为空。</p><div className="flex gap-3"><input type="text" placeholder="http://127.0.0.1:7890" value={proxy} onChange={event => onProxyChange(event.target.value)} className="flex-1 px-4 py-2.5 text-sm border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all" /><button onClick={onSaveProxy} className="px-6 py-2.5 bg-indigo-600 text-white text-sm font-semibold rounded-xl hover:bg-indigo-700 transition-colors">保存代理</button></div></div>
  </div>;
}
