// @generated by scripts/generate-contracts.mjs from contracts/watch-record.schema.json
// Do not edit by hand. Run npm run contracts:generate.

export const STATUS_VALUES = ["已看", "在看", "未看"] as const;
export type Status = typeof STATUS_VALUES[number];
export const MEDIA_TYPE_VALUES = ["电影", "剧集", "纪录片", "综艺", "动画"] as const;
export type MediaType = typeof MEDIA_TYPE_VALUES[number];
export const TMDB_MEDIA_KIND_VALUES = ["movie", "tv", "tv-season"] as const;
export type TmdbMediaKind = typeof TMDB_MEDIA_KIND_VALUES[number];
export const SERIES_RECORD_KIND_VALUES = ["season", "whole-series", "single-work"] as const;
export type SeriesRecordKind = typeof SERIES_RECORD_KIND_VALUES[number];

export interface WatchRecord {
  id: string;
  originalName: string;
  chineseName: string;
  progress: string;
  totalEpisodes: number | null;
  episodeTrackingEnabled?: boolean;
  nextEpisode?: number | null;
  movieProgress: number | null;
  movieDuration: number | null;
  releaseYear: string | null;
  posterPath: string | null;
  status: Status;
  platform: string;
  rating: number | null;
  startDate: string;
  endDate: string;
  notes: string;
  createdAt: string;
  updatedAt?: string | null;
  imdbId: string | null;
  isLocked?: boolean;
  genres?: string | null;
  originCountry?: string | null;
  imdbRating?: number | null;
  tmdbStatus?: string | null;
  interestLevel?: number | null;
  episodeRuntime?: number | null;
  mediaType: MediaType;
  contentTags?: string | null;
  tmdbMediaKind?: TmdbMediaKind | null;
  tmdbId?: number | null;
  tmdbParentId?: number | null;
  tmdbSeasonNumber?: number | null;
  seriesRecordKind?: SeriesRecordKind | null;
  rev?: number;
  revActor?: string;
}

export interface UpdateWatchRecord {
  originalName?: string;
  chineseName?: string;
  progress?: string;
  totalEpisodes?: number | null;
  movieProgress?: number | null;
  movieDuration?: number | null;
  releaseYear?: string | null;
  posterPath?: string | null;
  status?: Status;
  platform?: string;
  rating?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  notes?: string;
  imdbId?: string | null;
  isLocked?: boolean | null;
  genres?: string | null;
  originCountry?: string | null;
  imdbRating?: number | null;
  tmdbStatus?: string | null;
  interestLevel?: number | null;
  episodeRuntime?: number | null;
  mediaType?: MediaType;
  contentTags?: string | null;
  tmdbMediaKind?: TmdbMediaKind | null;
  tmdbId?: number | null;
  tmdbParentId?: number | null;
  tmdbSeasonNumber?: number | null;
  seriesRecordKind?: SeriesRecordKind | null;
}

export const WATCH_RECORD_UPDATE_FIELDS = [
  "originalName",
  "chineseName",
  "progress",
  "totalEpisodes",
  "movieProgress",
  "movieDuration",
  "releaseYear",
  "posterPath",
  "status",
  "platform",
  "rating",
  "startDate",
  "endDate",
  "notes",
  "imdbId",
  "isLocked",
  "genres",
  "originCountry",
  "imdbRating",
  "tmdbStatus",
  "interestLevel",
  "episodeRuntime",
  "mediaType",
  "contentTags",
  "tmdbMediaKind",
  "tmdbId",
  "tmdbParentId",
  "tmdbSeasonNumber",
  "seriesRecordKind"
] as const;
