import { useEffect, useRef, useState } from 'react';
import type { UpdateWatchRecord, WatchRecord } from '../../../shared/types';
import { createRecoveryPoint, completeMissingTmdbIdentity, getSettingAsync, getTmdbDetailAsync, searchTmdbAsync, setSettingAsync } from '../../../shared/lib/database';
import { type TmdbMedia } from '../../../shared/lib/classification';
import { BATCH_METADATA_STATE_KEY, buildBatchMetadataPatch, isBatchMetadataCandidate, missingBatchMetadataFields, noDataFieldsForRecord, parseBatchMetadataNoDataState, pruneBatchMetadataNoDataState, recordNoDataFields, remoteIdentityKey, retainMissingMetadataPatch, selectBatchMetadataPatch, selectTmdbMatch, tmdbTypeHintOf, type BatchMetadataField, type BatchMetadataNoDataState, type TmdbMatch } from '../../../shared/lib/batchMetadata';
import type { BatchApplyResult, BatchPlanRow } from './batchMetadataModel';
import type { NoticeTone } from '../../../shared/lib/feedback';

type BatchPhase = 'idle' | 'planning' | 'preview' | 'applying' | 'done';
const TMDB_IDENTITY_FIELDS = new Set<BatchMetadataField>(['tmdbMediaKind', 'tmdbId', 'tmdbParentId', 'tmdbSeasonNumber', 'seriesRecordKind']);
interface Options { records: WatchRecord[]; tmdbSaved: boolean; initialBatchNoDataState: BatchMetadataNoDataState; onUpdateRecord: (id: string, updates: UpdateWatchRecord) => Promise<void>; onDatabaseRestored: () => Promise<WatchRecord[]>; onNotify?: (tone: NoticeTone, message: string) => void; showFailure: (scope: string, action: string, error: unknown, setStatus?: (message: string) => void) => void; showSuccess: (message: string) => void; }

export function useBatchMetadata({ records, tmdbSaved, initialBatchNoDataState, onUpdateRecord, onDatabaseRestored, onNotify, showFailure, showSuccess }: Options) {
  const [batchNoDataState, setBatchNoDataState] = useState<BatchMetadataNoDataState>(initialBatchNoDataState);
  const [batchPhase, setBatchPhase] = useState<BatchPhase>('idle'); const [batchStatus, setBatchStatus] = useState(''); const [batchProgress, setBatchProgress] = useState(0); const [batchTotal, setBatchTotal] = useState(0);
  const [batchPlan, setBatchPlan] = useState<BatchPlanRow[]>([]); const [batchResults, setBatchResults] = useState<BatchApplyResult[]>([]); const [batchChoosingId, setBatchChoosingId] = useState<string | null>(null); const batchCancelRef = useRef(false); const recordsRef = useRef(records);
  useEffect(() => { recordsRef.current = records; }, [records]);
  // Bootstrap reads this once asynchronously; mirror that external snapshot without issuing a second IPC read.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { setBatchNoDataState(initialBatchNoDataState); }, [initialBatchNoDataState]);
  async function searchWithRetry(imdbId: string) { let last: unknown = new Error('TMDB search failed'); for (let i = 0; i < 3; i++) { if (batchCancelRef.current) throw new Error('Batch cancelled'); const response = await searchTmdbAsync({ query: imdbId, language: 'zh-CN' }); if (response.success) return response.results ?? []; last = new Error(response.error || 'TMDB search failed'); if (i < 2) await new Promise(r => setTimeout(r, 500 * (i + 1))); } throw last; }
  async function detailWithRetry(id: number, mediaType: 'movie' | 'tv') { let last: unknown = new Error('TMDB detail failed'); for (let i = 0; i < 3; i++) { if (batchCancelRef.current) throw new Error('Batch cancelled'); const response = await getTmdbDetailAsync({ id, mediaType, language: 'zh-CN' }); if (response.success && response.data) return response.data; last = new Error(response.error || 'TMDB detail failed'); if (i < 2) await new Promise(r => setTimeout(r, 500 * (i + 1))); } throw last; }
  const label = (result: TmdbMedia, match: TmdbMatch) => { const name = result.title || result.name || result.original_title || result.original_name || `TMDB #${match.id}`; const year = (result.release_date || result.first_air_date || '').split('-')[0]; return `${name}${year ? ` (${year})` : ''} · ${match.type === 'movie' ? '电影' : '剧集'} · #${match.id}`; };
  async function handlePrepare() {
    if (!tmdbSaved) { setBatchStatus('❌ 请先配置 TMDB API Key'); onNotify?.('warning', '请先配置 TMDB API Key。'); return; }
    let noDataState = pruneBatchMetadataNoDataState(parseBatchMetadataNoDataState(await getSettingAsync(BATCH_METADATA_STATE_KEY)), records); const targets = records.filter(r => isBatchMetadataCandidate(r, noDataFieldsForRecord(noDataState, r)));
    if (!targets.length) { setBatchNoDataState(noDataState); await setSettingAsync(BATCH_METADATA_STATE_KEY, JSON.stringify(noDataState)); setBatchStatus('🎉 所有未锁定且带 IMDb 编号的记录均无可补字段，或缺失字段已确认 TMDB 无数据。'); setTimeout(() => setBatchStatus(''), 3000); return; }
    batchCancelRef.current = false; setBatchPhase('planning'); setBatchPlan([]); setBatchResults([]); setBatchTotal(targets.length); setBatchProgress(0); setBatchStatus('正在分析缺失字段，不会写入数据库...'); const rows: BatchPlanRow[] = []; const searches = new Map<string, TmdbMedia[]>(); const details = new Map<string, TmdbMedia>();
    for (let index = 0; index < targets.length; index++) { if (batchCancelRef.current) break; const record = targets[index]; setBatchProgress(index + 1); setBatchStatus('正在分析: ' + record.chineseName);
      try { const imdbId = record.imdbId!.trim(); let searchResults = searches.get(imdbId); if (!searchResults) { searchResults = await searchWithRetry(imdbId); searches.set(imdbId, searchResults); } const matchResult = selectTmdbMatch(record, searchResults);
        if (!matchResult.ok) { const candidates = matchResult.candidates?.map(match => { const result = searchResults!.find(item => item.id === match.id && item.media_type === match.type); return { match, label: result ? label(result, match) : `TMDB #${match.id}` }; }); const hint = tmdbTypeHintOf(record); const prior = noDataFieldsForRecord(noDataState, record); const remaining = missingBatchMetadataFields(record, hint).filter(f => !prior.has(f)); const definitive = hint != null && !searchResults.some(result => result.media_type === hint && result.id); const noDataFields = definitive ? remaining : []; noDataState = recordNoDataFields(noDataState, record, noDataFields); rows.push({ recordId: record.id, recordName: record.chineseName || record.originalName || '未命名条目', status: candidates?.length ? 'choice' : 'skipped', updates: {}, fields: [], noDataFields, candidates, reason: noDataFields.length ? `${matchResult.reason}；缺失字段已记为无需再查` : matchResult.reason }); setBatchPlan([...rows]); continue; }
        const key = `${matchResult.match.type}:${matchResult.match.id}`; let detail = details.get(key); if (!detail) { detail = await detailWithRetry(matchResult.match.id, matchResult.match.type); details.set(key, detail); } const prior = noDataFieldsForRecord(noDataState, record); const allowed = new Set(missingBatchMetadataFields(record, matchResult.match.type).filter(f => !prior.has(f))); const patch = selectBatchMetadataPatch(buildBatchMetadataPatch(record, detail, matchResult.match.type), allowed); const noDataFields = [...allowed].filter(f => !patch.fields.includes(f) && !(patch.identityConflict && TMDB_IDENTITY_FIELDS.has(f))); noDataState = recordNoDataFields(noDataState, record, noDataFields); rows.push({ recordId: record.id, recordName: record.chineseName || record.originalName || '未命名条目', status: patch.fields.length ? 'ready' : 'skipped', updates: patch.updates, fields: patch.fields, noDataFields, remoteIdentity: remoteIdentityKey(matchResult.match, patch.seasonNumber), identityPlan: patch.identityPlan, identityConflict: patch.identityConflict, reason: patch.fields.length ? patch.identityConflict : patch.identityConflict || 'TMDB 没有返回可用于缺失字段的有效值，已记为无需再查' });
      } catch { if (batchCancelRef.current) break; onNotify?.('warning', 'TMDB 查询失败，可重新分析。'); rows.push({ recordId: record.id, recordName: record.chineseName || record.originalName || '未命名条目', status: 'failed', updates: {}, fields: [], reason: 'TMDB 查询失败，可重新分析' }); } setBatchPlan([...rows]); if (index + 1 < targets.length) await new Promise(r => setTimeout(r, 200)); }
    try { await setSettingAsync(BATCH_METADATA_STATE_KEY, JSON.stringify(noDataState)); setBatchNoDataState(noDataState); } catch (error) { showFailure('Settings.BatchMetadataNoDataState', '保存 TMDB 无数据状态', error); onNotify?.('warning', '补全预览已生成，但“TMDB 无数据”状态保存失败，下次可能再次查询。'); }
    setBatchPlan(rows); setBatchPhase('preview'); const ready = rows.filter(r => r.status === 'ready').length; const failed = rows.filter(r => r.status === 'failed').length; setBatchStatus(batchCancelRef.current ? `分析已取消；已完成 ${rows.length} / ${targets.length} 条，可检查已生成的预览。` : `分析完成：可更新 ${ready} 条，跳过/失败 ${rows.length - ready} 条${failed ? `（失败 ${failed} 条）` : ''}。`);
  }
  async function handleSelectCandidate(row: BatchPlanRow, match: TmdbMatch) { const record = recordsRef.current.find(r => r.id === row.recordId); if (!record) return; setBatchChoosingId(row.recordId); setBatchStatus(`正在读取所选条目：${row.recordName}`); try { const detail = await detailWithRetry(match.id, match.type); let state = pruneBatchMetadataNoDataState(parseBatchMetadataNoDataState(await getSettingAsync(BATCH_METADATA_STATE_KEY)), recordsRef.current); const prior = noDataFieldsForRecord(state, record); const allowed = new Set(missingBatchMetadataFields(record, match.type).filter(f => !prior.has(f))); const patch = selectBatchMetadataPatch(buildBatchMetadataPatch(record, detail, match.type), allowed); const noDataFields = [...allowed].filter(f => !patch.fields.includes(f) && !(patch.identityConflict && TMDB_IDENTITY_FIELDS.has(f))); state = recordNoDataFields(state, record, noDataFields); await setSettingAsync(BATCH_METADATA_STATE_KEY, JSON.stringify(state)); setBatchNoDataState(state); setBatchPlan(current => current.map(item => item.recordId === row.recordId ? { ...item, status: patch.fields.length ? 'ready' : 'skipped', updates: patch.updates, fields: patch.fields, noDataFields, candidates: undefined, remoteIdentity: remoteIdentityKey(match, patch.seasonNumber), identityPlan: patch.identityPlan, identityConflict: patch.identityConflict, reason: patch.fields.length ? patch.identityConflict : patch.identityConflict || '所选 TMDB 条目没有可用于缺失字段的有效值，已记为无需再查' } : item)); setBatchStatus(patch.fields.length ? '已生成所选条目的写入预览。' : '所选条目没有可补字段。'); } catch { setBatchStatus('❌ 读取所选 TMDB 条目失败，请重试选择。'); } finally { setBatchChoosingId(null); } }
  async function handleApply(plans?: BatchPlanRow[]) { const selected = plans ?? batchPlan.filter(r => r.status === 'ready'); if (!selected.length) { setBatchStatus('没有可写入的字段。'); return; } const actionable = selected.filter(p => { const current = recordsRef.current.find(r => r.id === p.recordId); return current && !current.isLocked && retainMissingMetadataPatch(current, p.updates).fields.length > 0; }).length; if (actionable >= 2) { setBatchStatus('正在创建批量写入前恢复点...'); try { await createRecoveryPoint('batch-metadata'); } catch (error) { showFailure('Settings.BatchMetadataRecoveryPoint', '创建批量写入前恢复点', error, setBatchStatus); return; } } batchCancelRef.current = false; setBatchPhase('applying'); setBatchProgress(0); setBatchTotal(selected.length); setBatchStatus('正在安全写入已确认的字段...'); const results: BatchApplyResult[] = plans ? batchResults.filter(r => !selected.some(p => p.recordId === r.plan.recordId)) : []; let identityUpdated = false;
    for (let index = 0; index < selected.length; index++) { if (batchCancelRef.current) break; const plan = selected[index]; setBatchProgress(index + 1); setBatchStatus('正在写入: ' + plan.recordName); const current = recordsRef.current.find(r => r.id === plan.recordId); if (!current || current.isLocked) { results.push({ plan, status: 'skipped', reason: current ? '记录已锁定' : '记录已不存在' }); setBatchResults([...results]); continue; } const safe = retainMissingMetadataPatch(current, plan.updates); if (!safe.fields.length) { results.push({ plan, status: 'skipped', reason: '预览后字段已被其他操作补全' }); setBatchResults([...results]); continue; } const ordinary = safe.fields.filter(f => !TMDB_IDENTITY_FIELDS.has(f)); const identity = safe.fields.filter(f => TMDB_IDENTITY_FIELDS.has(f)); let ordinaryWritten = false; try { if (ordinary.length) { const updates: UpdateWatchRecord = {}; for (const field of ordinary) Object.assign(updates, { [field]: safe.updates[field] }); await onUpdateRecord(plan.recordId, updates); ordinaryWritten = true; } let identityFailure: string | undefined; if (identity.length && plan.identityPlan) { try { await completeMissingTmdbIdentity({ recordId: plan.recordId, expectedRev: (current.rev ?? 0) + (ordinaryWritten ? 1 : 0), expectedImdbId: current.imdbId!, ...plan.identityPlan }); identityUpdated = true; } catch { identityFailure = 'TMDB 身份写入失败，可重新分析后重试'; } } const written = identityFailure ? ordinary : safe.fields; results.push({ plan: { ...plan, fields: written, updates: safe.updates }, status: written.length ? 'updated' : 'failed', reason: identityFailure }); } catch { results.push({ plan, status: 'failed', reason: '数据库写入失败，可重试此条' }); } setBatchResults([...results]); }
    if (identityUpdated) { try { await onDatabaseRestored(); } catch { onNotify?.('warning', 'TMDB 身份已写入，但界面刷新失败；重新打开程序后即可显示。'); } } if (batchCancelRef.current) { const done = new Set(results.map(r => r.plan.recordId)); selected.forEach(plan => { if (!done.has(plan.recordId)) results.push({ plan, status: 'skipped', reason: '用户取消，未写入' }); }); } setBatchResults(results); setBatchPhase('done'); const updated = results.filter(r => r.status === 'updated').length; const failed = results.filter(r => r.status === 'failed').length; const skipped = results.filter(r => r.status === 'skipped').length; setBatchStatus(`${batchCancelRef.current ? '补全已停止' : '补全结束'}：已更新 ${updated} 条，跳过 ${skipped} 条，失败 ${failed} 条。`); if (failed) onNotify?.('warning', `批量补全有 ${failed} 条写入失败，可单独重试。`); else if (updated) showSuccess(`已安全补全 ${updated} 条记录。`);
  }
  async function handleClearNoData() { if (!confirm('确定清除全部“TMDB 无数据”记忆吗？清除后，下次分析会重新查询这些缺失字段。')) return; try { const empty: BatchMetadataNoDataState = { version: 1, records: {} }; await setSettingAsync(BATCH_METADATA_STATE_KEY, JSON.stringify(empty)); setBatchNoDataState(empty); setBatchStatus('✅ 已清除 TMDB 无数据记忆。'); } catch (error) { showFailure('Settings.ClearBatchMetadataNoDataState', '清除 TMDB 无数据记忆', error, setBatchStatus); } }
  function handleCancel() { batchCancelRef.current = true; setBatchStatus(batchPhase === 'planning' ? '正在停止分析...' : '将在当前记录写入完成后停止...'); }
  function resetBatch() { batchCancelRef.current = false; setBatchPhase('idle'); setBatchPlan([]); setBatchResults([]); setBatchProgress(0); setBatchTotal(0); setBatchStatus(''); }
  return { batchNoDataState, batchPhase, batchStatus, batchProgress, batchTotal, batchPlan, batchResults, batchChoosingId, batchSyncing: batchPhase === 'planning' || batchPhase === 'applying', handlePrepare, handleApply, handleSelectCandidate, handleClearNoData, handleCancel, resetBatch, batchCancelRef };
}
